export interface GrammarEntry {
  id: number;
  structure: string;
  structureTranslation: string;
  example: string;
  exampleTranslation: string;
  notes?: string;
}

export const GRAMMAR_STRUCTURES: GrammarEntry[] = [
  {
    id: 1,
    structure: "AはBです。",
    structureTranslation: "A is B.",
    example: "彼（かれ）は学生（がくせい）です。",
    exampleTranslation: "He is a student.",
  },
  {
    id: 2,
    structure: "AはBではありません。",
    structureTranslation: "A is not B.",
    example: "今日（きょう）は休（やす）みではありません。",
    exampleTranslation: "Today is not a holiday.",
  },
  {
    id: 3,
    structure: "AはBですか。",
    structureTranslation: "Is A B?",
    example: "それは本当（ほんとう）ですか。",
    exampleTranslation: "Is that true?",
  },
  {
    id: 4,
    structure: "Aがあります。",
    structureTranslation: "There is A. (inanimate)",
    example: "机（つくえ）の上（うえ）に本（ほん）があります。",
    exampleTranslation: "There is a book on the desk.",
  },
  {
    id: 5,
    structure: "Aがいます。",
    structureTranslation: "There is A. (animate)",
    example: "公園（こうえん）に子供（こども）がいます。",
    exampleTranslation: "There are children in the park.",
  },
  {
    id: 6,
    structure: "Aをします。",
    structureTranslation: "Do A.",
    example: "毎朝（まいあさ）運動（うんどう）をします。",
    exampleTranslation: "I exercise every morning.",
  },
  {
    id: 7,
    structure: "Aへ行きます。",
    structureTranslation: "Go to A. (direction)",
    example: "学校（がっこう）へ行（い）きます。",
    exampleTranslation: "I go to school.",
  },
  {
    id: 8,
    structure: "Aに行きます。",
    structureTranslation: "Go to A. (destination)",
    example: "日本（にほん）に行（い）きます。",
    exampleTranslation: "I go to Japan.",
  },
  {
    id: 9,
    structure: "AからBまで",
    structureTranslation: "From A to B.",
    example: "東京（とうきょう）から大阪（おおさか）まで行（い）きます。",
    exampleTranslation: "I go from Tokyo to Osaka.",
  },
  {
    id: 10,
    structure: "AとB",
    structureTranslation: "A and B / with A.",
    example: "友達（ともだち）と映画（えいが）を見（み）ます。",
    exampleTranslation: "I watch a movie with a friend.",
  },
  {
    id: 11,
    structure: "AもBです。",
    structureTranslation: "A is also B.",
    example: "彼女（かのじょ）も学生（がくせい）です。",
    exampleTranslation: "She is also a student.",
  },
  {
    id: 12,
    structure: "AのB",
    structureTranslation: "B of A / A's B.",
    example: "日本（にほん）の文化（ぶんか）です。",
    exampleTranslation: "It is the culture of Japan.",
  },
  {
    id: 13,
    structure: "AよりBのほうがC",
    structureTranslation: "B is more C than A.",
    example: "電車（でんしゃ）より車（くるま）のほうが速（はや）いです。",
    exampleTranslation: "Cars are faster than trains.",
  },
  {
    id: 14,
    structure: "AはBよりC",
    structureTranslation: "A is more C than B.",
    example: "今日（きょう）は昨日（きのう）より寒（さむ）いです。",
    exampleTranslation: "Today is colder than yesterday.",
  },
  {
    id: 15,
    structure: "Aが一番C",
    structureTranslation: "A is the most C.",
    example: "これが一番（いちばん）好（す）きです。",
    exampleTranslation: "I like this the most.",
  },
  {
    id: 16,
    structure: "Aたいです",
    structureTranslation: "I want to do A.",
    example: "寿司（すし）を食（た）べたいです。",
    exampleTranslation: "I want to eat sushi.",
  },
  {
    id: 17,
    structure: "Aたことがある",
    structureTranslation: "I have done A before.",
    example: "京都（きょうと）へ行（い）ったことがあります。",
    exampleTranslation: "I have been to Kyoto before.",
  },
  {
    id: 18,
    structure: "Aている",
    structureTranslation: "A is happening / in a state of A.",
    example: "雨（あめ）が降（ふ）っています。",
    exampleTranslation: "It is raining.",
  },
  {
    id: 19,
    structure: "AてからB",
    structureTranslation: "After doing A, B.",
    example: "家（いえ）に帰（かえ）ってから勉強（べんきょう）します。",
    exampleTranslation: "After going home, I study.",
  },
  {
    id: 20,
    structure: "Aてもいいです",
    structureTranslation: "It is okay to do A.",
    example: "ここに座（すわ）ってもいいです。",
    exampleTranslation: "You may sit here.",
  },
  {
    id: 21,
    structure: "Aてはいけません",
    structureTranslation: "You must not do A.",
    example: "ここで写真（しゃしん）を撮（と）ってはいけません。",
    exampleTranslation: "You must not take photos here.",
  },
  {
    id: 22,
    structure: "Aなければならない",
    structureTranslation: "Must do A.",
    example: "行（い）かなければなりません。",
    exampleTranslation: "I must go.",
  },
  {
    id: 23,
    structure: "Aなくてもいい",
    structureTranslation: "It is okay not to do A.",
    example: "来（こ）なくてもいいです。",
    exampleTranslation: "You don't have to come.",
  },
  {
    id: 24,
    structure: "Aと思います",
    structureTranslation: "I think A.",
    example: "それは正（ただ）しいと思（おも）います。",
    exampleTranslation: "I think that is correct.",
  },
  {
    id: 25,
    structure: "Aと言っています",
    structureTranslation: "Someone is saying A.",
    example: "彼（かれ）は行（い）くと言（い）っています。",
    exampleTranslation: "He is saying he will go.",
  },
  {
    id: 26,
    structure: "Aようです",
    structureTranslation: "It seems like A.",
    example: "雨（あめ）が降（ふ）りそうなようです。",
    exampleTranslation: "It seems like it might rain.",
  },
  {
    id: 27,
    structure: "Aそうです",
    structureTranslation: "I heard that A.",
    example: "彼（かれ）は来（く）るそうです。",
    exampleTranslation: "I heard that he is coming.",
    notes: "hearsay",
  },
  {
    id: 28,
    structure: "Aそうです",
    structureTranslation: "It looks like A.",
    example: "おいしそうです。",
    exampleTranslation: "It looks delicious.",
    notes: "appearance",
  },
  {
    id: 29,
    structure: "Aかもしれません",
    structureTranslation: "A might happen / might be the case.",
    example: "雨（あめ）が降（ふ）るかもしれません。",
    exampleTranslation: "It might rain.",
  },
  {
    id: 30,
    structure: "Aでしょう",
    structureTranslation: "A is probably the case.",
    example: "明日（あした）は晴（は）れるでしょう。",
    exampleTranslation: "It will probably be sunny tomorrow.",
  },
  {
    id: 31,
    structure: "AためにB",
    structureTranslation: "B in order to A / for the sake of A.",
    example: "健康（けんこう）のために運動（うんどう）します。",
    exampleTranslation: "I exercise for my health.",
  },
  {
    id: 32,
    structure: "AのでB",
    structureTranslation: "B because A. (objective reason)",
    example: "雨（あめ）が降（ふ）ったので帰（かえ）りました。",
    exampleTranslation: "I went home because it rained.",
  },
  {
    id: 33,
    structure: "AからB",
    structureTranslation: "B because A. (subjective reason)",
    example: "寒（さむ）いから窓（まど）を閉（し）めます。",
    exampleTranslation: "I will close the window because it is cold.",
    notes: "reason",
  },
  {
    id: 34,
    structure: "AけれどもB",
    structureTranslation: "A, but B.",
    example: "高（たか）いけれども買（か）いました。",
    exampleTranslation: "It was expensive, but I bought it.",
  },
  {
    id: 35,
    structure: "AのにB",
    structureTranslation: "Even though A, B.",
    example: "安（やす）いのに買（か）いません。",
    exampleTranslation: "Even though it is cheap, I won't buy it.",
    notes: "contrast",
  },
  {
    id: 36,
    structure: "AながらB",
    structureTranslation: "B while doing A.",
    example: "音楽（おんがく）を聞（き）きながら勉強（べんきょう）します。",
    exampleTranslation: "I study while listening to music.",
  },
  {
    id: 37,
    structure: "AしBし",
    structureTranslation: "A and also B. (listing reasons)",
    example: "安（やす）いし便利（べんり）です。",
    exampleTranslation: "It is cheap and also convenient.",
  },
  {
    id: 38,
    structure: "AたりBたりする",
    structureTranslation: "Do things like A and B.",
    example: "日曜日（にちようび）は読書（どくしょ）したり寝（ね）たりします。",
    exampleTranslation: "On Sundays, I do things like read and sleep.",
  },
  {
    id: 39,
    structure: "AばB",
    structureTranslation: "If A, then B.",
    example: "雨（あめ）が降（ふ）れば行（い）きません。",
    exampleTranslation: "If it rains, I won't go.",
  },
  {
    id: 40,
    structure: "AならB",
    structureTranslation: "If A is the case, then B.",
    example: "時間（じかん）があるなら行（い）きます。",
    exampleTranslation: "If you have time, I will go.",
  },
  {
    id: 41,
    structure: "AとB",
    structureTranslation: "Whenever A, B. (natural consequence)",
    example: "春（はる）になると花（はな）が咲（さ）きます。",
    exampleTranslation: "When spring comes, flowers bloom.",
    notes: "conditional",
  },
  {
    id: 42,
    structure: "Aてしまう",
    structureTranslation: "End up doing A / do A completely.",
    example: "宿題（しゅくだい）を忘（わす）れてしまいました。",
    exampleTranslation: "I ended up forgetting my homework.",
  },
  {
    id: 43,
    structure: "Aておく",
    structureTranslation: "Do A in advance / do A for later.",
    example: "予約（よやく）しておきます。",
    exampleTranslation: "I will make a reservation in advance.",
  },
  {
    id: 44,
    structure: "Aてみる",
    structureTranslation: "Try doing A.",
    example: "食（た）べてみます。",
    exampleTranslation: "I will try eating it.",
  },
  {
    id: 45,
    structure: "Aてくる",
    structureTranslation: "A has started happening / A comes toward.",
    example: "雨（あめ）が降（ふ）ってきました。",
    exampleTranslation: "It started raining.",
  },
  {
    id: 46,
    structure: "Aていく",
    structureTranslation: "A continues into the future / A goes away.",
    example: "人（ひと）が増（ふ）えていきます。",
    exampleTranslation: "The number of people will keep increasing.",
  },
  {
    id: 47,
    structure: "Aられる",
    structureTranslation: "A is done (to someone). (passive)",
    example: "先生（せんせい）にほめられました。",
    exampleTranslation: "I was praised by the teacher.",
    notes: "passive",
  },
  {
    id: 48,
    structure: "Aられる",
    structureTranslation: "Can do A. (potential)",
    example: "漢字（かんじ）が読（よ）めます。",
    exampleTranslation: "I can read kanji.",
    notes: "potential",
  },
  {
    id: 49,
    structure: "Aさせる",
    structureTranslation: "Make/let someone do A. (causative)",
    example: "子供（こども）を行（い）かせます。",
    exampleTranslation: "I will let the child go.",
  },
  {
    id: 50,
    structure: "Aさせられる",
    structureTranslation: "Be made to do A. (causative passive)",
    example: "残業（ざんぎょう）させられました。",
    exampleTranslation: "I was made to work overtime.",
  },
  {
    id: 51,
    structure: "Aことができる",
    structureTranslation: "Can do A / be able to do A.",
    example: "泳（およ）ぐことができます。",
    exampleTranslation: "I can swim.",
  },
  {
    id: 52,
    structure: "Aことにする",
    structureTranslation: "Decide to do A.",
    example: "毎朝（まいあさ）走（はし）ることにします。",
    exampleTranslation: "I will decide to run every morning.",
  },
  {
    id: 53,
    structure: "Aことになる",
    structureTranslation: "It has been decided that A.",
    example: "来月（らいげつ）転勤（てんきん）することになりました。",
    exampleTranslation: "It has been decided that I will transfer next month.",
  },
  {
    id: 54,
    structure: "Aようになる",
    structureTranslation: "Reach the point where A.",
    example: "日本語（にほんご）が話（はな）せるようになりました。",
    exampleTranslation: "I have become able to speak Japanese.",
  },
  {
    id: 55,
    structure: "Aためだ",
    structureTranslation: "It is because of A.",
    example: "失敗（しっぱい）したのは準備（じゅんび）不足（ぶそく）のためです。",
    exampleTranslation: "The failure was due to lack of preparation.",
  },
  {
    id: 56,
    structure: "AはBと呼ばれる",
    structureTranslation: "A is called B.",
    example: "彼（かれ）は天才（てんさい）と呼（よ）ばれています。",
    exampleTranslation: "He is called a genius.",
  },
  {
    id: 57,
    structure: "AはBとして知られている",
    structureTranslation: "A is known as B.",
    example: "京都（きょうと）は古都（こと）として知（し）られています。",
    exampleTranslation: "Kyoto is known as an ancient capital.",
  },
  {
    id: 58,
    structure: "AはBとされている",
    structureTranslation: "A is regarded as B.",
    example: "それは危険（きけん）だとされています。",
    exampleTranslation: "That is regarded as dangerous.",
  },
  {
    id: 59,
    structure: "Aに違いない",
    structureTranslation: "A must be the case. (strong certainty)",
    example: "彼（かれ）が犯人（はんにん）に違（ちが）いない。",
    exampleTranslation: "He must be the culprit.",
  },
  {
    id: 60,
    structure: "Aはずだ",
    structureTranslation: "A should be the case. (expectation)",
    example: "彼（かれ）は来（く）るはずです。",
    exampleTranslation: "He should be coming.",
  },
  {
    id: 61,
    structure: "Aわけではない",
    structureTranslation: "It is not that A.",
    example: "嫌（きら）いなわけではありません。",
    exampleTranslation: "It's not that I dislike it.",
  },
  {
    id: 62,
    structure: "Aわけがない",
    structureTranslation: "There is no way A.",
    example: "そんなはずがありません。",
    exampleTranslation: "There is no way that's the case.",
  },
  {
    id: 63,
    structure: "AようにB",
    structureTranslation: "B so that A. (purpose)",
    example: "忘（わす）れないように書（か）きます。",
    exampleTranslation: "I write it down so that I won't forget.",
    notes: "purpose",
  },
  {
    id: 64,
    structure: "Aようだ",
    structureTranslation: "It is like A. (simile)",
    example: "夢（ゆめ）のようです。",
    exampleTranslation: "It is like a dream.",
    notes: "simile",
  },
  {
    id: 65,
    structure: "AにとってB",
    structureTranslation: "B for A / from A's perspective.",
    example: "私（わたし）にとって大切（たいせつ）です。",
    exampleTranslation: "It is important to me.",
  },
  {
    id: 66,
    structure: "AについてB",
    structureTranslation: "B about A / regarding A.",
    example: "歴史（れきし）について話（はな）します。",
    exampleTranslation: "I will talk about history.",
  },
  {
    id: 67,
    structure: "Aに対してB",
    structureTranslation: "B toward A / against A.",
    example: "彼（かれ）に対（たい）して失礼（しつれい）です。",
    exampleTranslation: "That is rude toward him.",
  },
  {
    id: 68,
    structure: "AによってB",
    structureTranslation: "B depends on A / B differs by A.",
    example: "文化（ぶんか）は国（くに）によって違（ちが）います。",
    exampleTranslation: "Culture differs depending on the country.",
  },
  {
    id: 69,
    structure: "AによりB",
    structureTranslation: "B due to A. (formal/written)",
    example: "事故（じこ）により電車（でんしゃ）が遅（おく）れました。",
    exampleTranslation: "The train was delayed due to an accident.",
    notes: "formal",
  },
  {
    id: 70,
    structure: "Aを通してB",
    structureTranslation: "B through A.",
    example: "仕事（しごと）を通（とお）して学（まな）びました。",
    exampleTranslation: "I learned through work.",
  },
  {
    id: 71,
    structure: "AにおいてB",
    structureTranslation: "B at/in A. (formal)",
    example: "会議（かいぎ）において発表（はっぴょう）します。",
    exampleTranslation: "I will present at the meeting.",
  },
  {
    id: 72,
    structure: "Aに関してB",
    structureTranslation: "B regarding A / concerning A.",
    example: "その件（けん）に関（かん）して説明（せつめい）します。",
    exampleTranslation: "I will explain regarding that matter.",
  },
  {
    id: 73,
    structure: "Aに違いありません",
    structureTranslation: "A is undoubtedly the case.",
    example: "彼（かれ）が正（ただ）しいに違（ちが）いありません。",
    exampleTranslation: "He is undoubtedly correct.",
  },
  {
    id: 74,
    structure: "AというB",
    structureTranslation: "B called A / B known as A.",
    example: "これは日本（にほん）という国（くに）です。",
    exampleTranslation: "This is a country called Japan.",
  },
  {
    id: 75,
    structure: "AといえばB",
    structureTranslation: "Speaking of A, B.",
    example: "京都（きょうと）といえば寺（てら）です。",
    exampleTranslation: "Speaking of Kyoto, it's temples.",
  },
  {
    id: 76,
    structure: "Aということだ",
    structureTranslation: "It means A / the situation is A.",
    example: "中止（ちゅうし）ということです。",
    exampleTranslation: "It means it is cancelled.",
  },
  {
    id: 77,
    structure: "Aことだ",
    structureTranslation: "You should do A. (advice)",
    example: "早（はや）く寝（ね）ることです。",
    exampleTranslation: "You should go to bed early.",
    notes: "advice",
  },
  {
    id: 78,
    structure: "Aものだ",
    structureTranslation: "Used to do A. (nostalgia)",
    example: "よく遊（あそ）んだものです。",
    exampleTranslation: "We used to play a lot.",
    notes: "nostalgia",
  },
  {
    id: 79,
    structure: "Aものだ",
    structureTranslation: "It is natural that A.",
    example: "子供（こども）は泣（な）くものです。",
    exampleTranslation: "It is natural for children to cry.",
    notes: "common sense",
  },
  {
    id: 80,
    structure: "Aにすぎない",
    structureTranslation: "A is nothing more than / merely A.",
    example: "それは噂（うわさ）にすぎません。",
    exampleTranslation: "That is nothing more than a rumor.",
  },
  {
    id: 81,
    structure: "Aにほかならない",
    structureTranslation: "A is nothing other than / precisely A.",
    example: "成功（せいこう）は努力（どりょく）にほかなりません。",
    exampleTranslation: "Success is nothing other than effort.",
  },
  {
    id: 82,
    structure: "AどころかB",
    structureTranslation: "Far from A, B.",
    example: "一人（ひとり）どころか誰（だれ）も来（き）ません。",
    exampleTranslation: "Far from one person, nobody is coming.",
  },
  {
    id: 83,
    structure: "AばかりでなくB",
    structureTranslation: "Not only A, but also B.",
    example: "彼（かれ）は英語（えいご）ばかりでなく中国語（ちゅうごくご）も話（はな）せます。",
    exampleTranslation: "He can speak not only English but also Chinese.",
  },
  {
    id: 84,
    structure: "AだけでなくB",
    structureTranslation: "Not only A, but also B.",
    example: "彼女（かのじょ）は親切（しんせつ）だけでなく美（うつく）しいです。",
    exampleTranslation: "She is not only kind but also beautiful.",
  },
  {
    id: 85,
    structure: "AずにB",
    structureTranslation: "B without doing A.",
    example: "朝食（ちょうしょく）を食（た）べずに出（で）かけました。",
    exampleTranslation: "I went out without eating breakfast.",
  },
  {
    id: 86,
    structure: "AままB",
    structureTranslation: "B while remaining in the state of A.",
    example: "靴（くつ）を履（は）いたまま寝（ね）ました。",
    exampleTranslation: "I fell asleep with my shoes on.",
  },
  {
    id: 87,
    structure: "AことなくB",
    structureTranslation: "B without ever doing A.",
    example: "休（やす）むことなく働（はたら）きました。",
    exampleTranslation: "I worked without ever resting.",
  },
  {
    id: 88,
    structure: "Aかどうか",
    structureTranslation: "Whether or not A.",
    example: "行（い）くかどうか分（わ）かりません。",
    exampleTranslation: "I don't know whether or not I will go.",
  },
  {
    id: 89,
    structure: "AほどBない",
    structureTranslation: "B is not as much as A.",
    example: "彼（かれ）ほど速（はや）く走（はし）れません。",
    exampleTranslation: "I can't run as fast as him.",
  },
  {
    id: 90,
    structure: "Aばかりだ",
    structureTranslation: "A keeps getting worse / only A.",
    example: "物価（ぶっか）は上（あ）がるばかりです。",
    exampleTranslation: "Prices just keep going up.",
    notes: "worsening",
  },
  {
    id: 91,
    structure: "Aつもりだ",
    structureTranslation: "I intend to do A.",
    example: "行（い）くつもりです。",
    exampleTranslation: "I intend to go.",
  },
  {
    id: 92,
    structure: "A予定だ",
    structureTranslation: "A is planned / scheduled.",
    example: "明日（あした）出発（しゅっぱつ）する予定（よてい）です。",
    exampleTranslation: "I am scheduled to depart tomorrow.",
  },
];
